const zone = (type, row, cells) => ({ type, row, cells })

export const roleMeta = {
  data: { label: 'Datos', color: '#f6dc59' },
  entry: { label: 'Entrada', color: '#87ca62' },
  exit: { label: 'Salida', color: '#ec82ad' },
  stock: { label: 'Existencia', color: '#f4a146' },
  unit: { label: 'Precio unitario', color: '#9ed7e4' },
  calculation: { label: 'Cuentas y resultados', color: '#9f7aca' },
}

export const zoneMeta = {
  data: roleMeta.data,
  entry: roleMeta.entry,
  exit: roleMeta.exit,
  stock: roleMeta.stock,
}

export const uepsLessons = [
  {
    chapter: 'Guía',
    role: 'calculation',
    phase: 'Antes de empezar',
    title: 'Cómo leer la ficha UEPS',
    intro: 'Último en entrar, primero en salir.',
    accent: '#9f7aca',
    facts: [
      ['Regla principal', 'En una venta usamos primero el lote más nuevo.'],
      ['Código de color', 'Cada color señala una zona distinta de la ficha.'],
    ],
    formula: ['UEPS', 'ÚLTIMO EN ENTRAR', 'PRIMERO EN SALIR'],
    formulaRoles: ['calculation', 'calculation'],
    note: 'El precio de venta no es el costo de salida: el costo se busca en la existencia anterior.',
    zones: [],
  },
  {
    chapter: 'O',
    role: 'data',
    phase: 'O · Paso 1 de 3',
    title: 'Buscar los datos de la compra',
    intro: 'El 3/05 compramos 950 unidades a $110 cada una, según Factura Original 635.',
    accent: '#f6dc59',
    facts: [['Fecha', '3/05'], ['Detalle', 'Factura Original 635']],
    formula: ['Palabra clave', 'COMPRAMOS', 'ENTRADA'],
    formulaRoles: ['data', 'entry'],
    note: 'Primero ubicamos la fecha y el comprobante en la zona Datos.',
    zones: [zone('data', 'Fila nueva · 3/05', [['Fecha', '3/05'], ['Detalle', 'Factura Original 635']])],
  },
  {
    chapter: 'O',
    role: 'entry',
    phase: 'O · Paso 2 de 3',
    title: 'Completar la entrada',
    intro: 'Copiamos la cantidad y el precio unitario del ejercicio.',
    accent: '#87ca62',
    facts: [['Cantidad', '950 unidades'], ['Precio unitario', '$110']],
    formula: ['Precio total', '950 × $110', '$104.500'],
    formulaRoles: ['calculation', 'calculation'],
    note: 'Los tres datos de la compra quedan juntos en Entrada.',
    zones: [zone('entry', 'Fila del 3/05', [['Cantidad', '950'], ['Precio unitario', '$110'], ['Precio total', '$104.500']])],
  },
  {
    chapter: 'O',
    role: 'stock',
    phase: 'O · Paso 3 de 3',
    title: 'Completar la existencia',
    intro: 'Es la primera operación: antes no había mercadería.',
    accent: '#f4a146',
    facts: [['Lote que queda', '950 unidades a $110'], ['Cantidad total', '950 unidades']],
    formula: ['Existencia', '950 × $110', '$104.500'],
    formulaRoles: ['stock', 'stock'],
    note: 'Como todavía no hubo ventas, la existencia repite el único lote comprado.',
    zones: [zone('stock', 'Fila del 3/05', [['Cantidad', '950'], ['Precio unitario', '950 a $110'], ['Precio total', '$104.500']])],
  },
  {
    chapter: 'P',
    role: 'data',
    phase: 'P · Paso 1 de 3',
    title: 'Buscar la segunda compra',
    intro: 'El 5/05 compramos 200 unidades a $125 cada una, según Factura Original 640.',
    accent: '#f6dc59',
    facts: [['Fecha', '5/05'], ['Detalle', 'Factura Original 640']],
    formula: ['Palabra clave', 'COMPRAMOS', 'ENTRADA'],
    formulaRoles: ['data', 'entry'],
    note: 'Abrimos una fila nueva y comenzamos por la zona Datos.',
    zones: [zone('data', 'Fila nueva · 5/05', [['Fecha', '5/05'], ['Detalle', 'Factura Original 640']])],
  },
  {
    chapter: 'P',
    role: 'entry',
    phase: 'P · Paso 2 de 3',
    title: 'Registrar la segunda entrada',
    intro: 'La nueva compra entra como un lote separado.',
    accent: '#87ca62',
    facts: [['Cantidad', '200 unidades'], ['Precio unitario', '$125']],
    formula: ['Precio total', '200 × $125', '$25.000'],
    formulaRoles: ['calculation', 'calculation'],
    note: 'No mezclamos los precios: cada compra conserva su propio costo.',
    zones: [zone('entry', 'Fila del 5/05', [['Cantidad', '200'], ['Precio unitario', '$125'], ['Precio total', '$25.000']])],
  },
  {
    chapter: 'P',
    role: 'stock',
    phase: 'P · Paso 3 de 3',
    title: 'Actualizar los lotes',
    intro: 'Sumamos cantidades y conservamos los dos costos.',
    accent: '#f4a146',
    facts: [['Cantidad', '950 + 200 = 1.150'], ['Lotes', '950 a $110 · 200 a $125']],
    formula: ['Precio total', '$104.500 + $25.000', '$129.500'],
    formulaRoles: ['calculation', 'calculation'],
    note: 'El lote de $125 es ahora el último en entrar.',
    zones: [zone('stock', 'Fila del 5/05', [['Cantidad', '1.150'], ['Precio unitario', '950 a $110\n200 a $125'], ['Precio total', '$129.500']])],
  },
  {
    chapter: 'Q',
    role: 'data',
    phase: 'Q · Paso 1 de 3',
    title: 'Ubicar los datos de la venta',
    intro: 'El 8/05 vendemos 850 unidades a $140 cada una, según Factura Duplicado 650.',
    accent: '#f6dc59',
    facts: [['Cantidad que sale', '850 unidades'], ['Precio de venta', '$140 por unidad']],
    formula: ['Palabra clave', 'VENDEMOS', 'SALIDA'],
    formulaRoles: ['data', 'exit'],
    note: '$140 es precio de venta. El costo se calcula con los lotes guardados.',
    zones: [
      zone('data', 'Fila nueva · 8/05', [['Fecha', '8/05'], ['Detalle', 'Factura Duplicado 650']]),
      zone('exit', 'Misma fila · 8/05', [['Cantidad', '850'], ['Precio unitario', 'Por calcular'], ['Precio total', 'Por calcular']]),
    ],
  },
  {
    chapter: 'Q',
    role: 'exit',
    phase: 'Q · Paso 2 de 3',
    title: 'Resolver la salida con UEPS',
    intro: 'Usamos primero las 200 unidades del lote más nuevo y completamos con 650 del anterior.',
    accent: '#ec82ad',
    facts: [['Último lote', '200 × $125 = $25.000'], ['Lote anterior', '650 × $110 = $71.500']],
    formula: ['Costo de salida', '$25.000 + $71.500', '$96.500'],
    formulaRoles: ['calculation', 'calculation'],
    note: 'La salida muestra qué cantidades y costos se usaron.',
    zones: [zone('exit', 'Fila del 8/05', [['Cantidad', '850'], ['Precio unitario', '200 a $125\n650 a $110'], ['Precio total', '$96.500']])],
  },
  {
    chapter: 'Q',
    role: 'stock',
    phase: 'Q · Paso 3 de 3',
    title: 'Descubrir qué lote quedó',
    intro: 'El lote de $125 se usó completo; del lote de $110 quedan 300 unidades.',
    accent: '#f4a146',
    facts: [['Cantidad restante', '1.150 − 850 = 300'], ['Lote restante', '300 unidades a $110']],
    formula: ['Existencia', '300 × $110', '$33.000'],
    formulaRoles: ['stock', 'stock'],
    note: 'Después de la venta queda un solo lote.',
    zones: [zone('stock', 'Fila del 8/05', [['Cantidad', '300'], ['Precio unitario', '300 a $110'], ['Precio total', '$33.000']])],
  },
  {
    chapter: 'R',
    role: 'data',
    phase: 'R · Paso 1 de 3',
    title: 'Buscar la nueva compra',
    intro: 'El 10/05 compramos 220 unidades a $130 cada una, según Factura Original 645.',
    accent: '#f6dc59',
    facts: [['Fecha', '10/05'], ['Detalle', 'Factura Original 645']],
    formula: ['Palabra clave', 'COMPRAMOS', 'ENTRADA'],
    formulaRoles: ['data', 'entry'],
    note: 'La compra comienza en una fila nueva de Datos.',
    zones: [zone('data', 'Fila nueva · 10/05', [['Fecha', '10/05'], ['Detalle', 'Factura Original 645']])],
  },
  {
    chapter: 'R',
    role: 'entry',
    phase: 'R · Paso 2 de 3',
    title: 'Completar la nueva entrada',
    intro: 'Registramos el lote de 220 unidades a $130.',
    accent: '#87ca62',
    facts: [['Cantidad', '220 unidades'], ['Precio unitario', '$130']],
    formula: ['Precio total', '220 × $130', '$28.600'],
    formulaRoles: ['calculation', 'calculation'],
    note: 'Esta compra pasa a ser el lote más nuevo.',
    zones: [zone('entry', 'Fila del 10/05', [['Cantidad', '220'], ['Precio unitario', '$130'], ['Precio total', '$28.600']])],
  },
  {
    chapter: 'R',
    role: 'stock',
    phase: 'R · Paso 3 de 3',
    title: 'Actualizar la existencia',
    intro: 'Sumamos el lote anterior y la compra nueva sin mezclar sus costos.',
    accent: '#f4a146',
    facts: [['Cantidad', '300 + 220 = 520'], ['Lotes', '300 a $110 · 220 a $130']],
    formula: ['Precio total', '$33.000 + $28.600', '$61.600'],
    formulaRoles: ['calculation', 'calculation'],
    note: 'El lote de $130 queda listo para salir primero.',
    zones: [zone('stock', 'Fila del 10/05', [['Cantidad', '520'], ['Precio unitario', '300 a $110\n220 a $130'], ['Precio total', '$61.600']])],
  },
  {
    chapter: 'S',
    role: 'data',
    phase: 'S · Paso 1 de 3',
    title: 'Ubicar la segunda venta',
    intro: 'El 12/05 vendemos 150 unidades a $165 cada una, según Factura Duplicado 658.',
    accent: '#f6dc59',
    facts: [['Cantidad que sale', '150 unidades'], ['Precio de venta', '$165 por unidad']],
    formula: ['Palabra clave', 'VENDEMOS', 'SALIDA'],
    formulaRoles: ['data', 'exit'],
    note: '$165 no se usa como costo: volvemos a mirar la existencia anterior.',
    zones: [
      zone('data', 'Fila nueva · 12/05', [['Fecha', '12/05'], ['Detalle', 'Factura Duplicado 658']]),
      zone('exit', 'Misma fila · 12/05', [['Cantidad', '150'], ['Precio unitario', 'Por calcular'], ['Precio total', 'Por calcular']]),
    ],
  },
  {
    chapter: 'S',
    role: 'exit',
    phase: 'S · Paso 2 de 3',
    title: 'Elegir el lote que sale',
    intro: 'El lote más nuevo tiene 220 unidades a $130 y alcanza para cubrir toda la venta.',
    accent: '#ec82ad',
    facts: [['Salida completa', '150 unidades a $130'], ['Quedan de ese lote', '220 − 150 = 70']],
    formula: ['Costo de salida', '150 × $130', '$19.500'],
    formulaRoles: ['calculation', 'calculation'],
    note: 'No tocamos el lote anterior de 300 unidades a $110.',
    zones: [zone('exit', 'Fila del 12/05', [['Cantidad', '150'], ['Precio unitario', '150 a $130'], ['Precio total', '$19.500']])],
  },
  {
    chapter: 'S',
    role: 'stock',
    phase: 'S · Paso 3 de 3',
    title: 'Actualizar la existencia final',
    intro: 'Quedan 300 unidades del lote anterior y 70 del lote más nuevo.',
    accent: '#f4a146',
    facts: [['Cantidad final', '520 − 150 = 370'], ['Lotes finales', '300 a $110 · 70 a $130']],
    formula: ['Existencia final', '$33.000 + $9.100', '$42.100'],
    formulaRoles: ['stock', 'stock'],
    note: 'Resultado: 370 unidades por un valor total de $42.100.',
    zones: [zone('stock', 'Fila del 12/05', [['Cantidad', '370'], ['Precio unitario', '300 a $110\n70 a $130'], ['Precio total', '$42.100']])],
  },
]

const pepsVariants = {
  0: {
    title: 'Cómo leer la ficha PEPS',
    intro: 'Primero en entrar, primero en salir.',
    facts: [
      ['Regla principal', 'En una venta usamos primero el lote más antiguo.'],
      ['Código de color', 'Cada color señala una zona distinta de la ficha.'],
    ],
    formula: ['PEPS', 'PRIMERO EN ENTRAR', 'PRIMERO EN SALIR'],
  },
  8: {
    title: 'Resolver la salida con PEPS',
    intro: 'Usamos 850 unidades del lote más antiguo, comprado a $110.',
    facts: [['Primer lote', '850 × $110 = $93.500'], ['Lote más nuevo', 'No se usa en esta salida']],
    formula: ['Costo de salida', '850 × $110', '$93.500'],
    note: 'En PEPS sale primero el lote de $110, porque fue el primero en entrar.',
    zones: [zone('exit', 'Fila del 8/05', [['Cantidad', '850'], ['Precio unitario', '850 a $110'], ['Precio total', '$93.500']])],
  },
  9: {
    title: 'Descubrir qué lotes quedaron',
    intro: 'Del lote de $110 quedan 100 unidades; el lote de $125 se mantiene completo.',
    facts: [['Cantidad restante', '1.150 − 850 = 300'], ['Lotes restantes', '100 a $110 · 200 a $125']],
    formula: ['Existencia', '$11.000 + $25.000', '$36.000'],
    note: 'Después de la venta quedan 100 unidades del primer lote y las 200 del segundo.',
    zones: [zone('stock', 'Fila del 8/05', [['Cantidad', '300'], ['Precio unitario', '100 a $110\n200 a $125'], ['Precio total', '$36.000']])],
  },
  12: {
    intro: 'Sumamos los dos lotes anteriores y la compra nueva sin mezclar sus costos.',
    facts: [['Cantidad', '300 + 220 = 520'], ['Lotes', '100 a $110 · 200 a $125 · 220 a $130']],
    formula: ['Precio total', '$36.000 + $28.600', '$64.600'],
    note: 'En PEPS el lote de $110 sigue siendo el primero que debe salir.',
    zones: [zone('stock', 'Fila del 10/05', [['Cantidad', '520'], ['Precio unitario', '100 a $110\n200 a $125\n220 a $130'], ['Precio total', '$64.600']])],
  },
  14: {
    title: 'Elegir los lotes que salen',
    intro: 'Salen primero las 100 unidades a $110; completamos con 50 unidades a $125.',
    facts: [['Primer lote', '100 × $110 = $11.000'], ['Segundo lote', '50 × $125 = $6.250']],
    formula: ['Costo de salida', '$11.000 + $6.250', '$17.250'],
    note: 'El lote de $130 no se toca porque entró último.',
    zones: [zone('exit', 'Fila del 12/05', [['Cantidad', '150'], ['Precio unitario', '100 a $110\n50 a $125'], ['Precio total', '$17.250']])],
  },
  15: {
    intro: 'Quedan 150 unidades a $125 y las 220 unidades a $130.',
    facts: [['Cantidad final', '520 − 150 = 370'], ['Lotes finales', '150 a $125 · 220 a $130']],
    formula: ['Existencia final', '$18.750 + $28.600', '$47.350'],
    note: 'Resultado: 370 unidades por un valor total de $47.350.',
    zones: [zone('stock', 'Fila del 12/05', [['Cantidad', '370'], ['Precio unitario', '150 a $125\n220 a $130'], ['Precio total', '$47.350']])],
  },
}

export const pepsLessons = uepsLessons.map((lesson, index) => (
  pepsVariants[index] ? { ...lesson, ...pepsVariants[index] } : lesson
))

export const lessonsByMethod = {
  UEPS: uepsLessons,
  PEPS: pepsLessons,
}

export const chapters = [
  { code: 'Guía', title: 'Cómo leer la ficha', start: 0, end: 0, role: 'calculation' },
  { code: 'O', title: 'Primera compra', start: 1, end: 3, role: 'entry' },
  { code: 'P', title: 'Segunda compra', start: 4, end: 6, role: 'entry' },
  { code: 'Q', title: 'Primera venta', start: 7, end: 9, role: 'exit' },
  { code: 'R', title: 'Nueva compra', start: 10, end: 12, role: 'entry' },
  { code: 'S', title: 'Venta y resultado final', start: 13, end: 15, role: 'exit' },
]
